CREATE TABLE SERVICE_METRICS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SERVICE_NAME VARCHAR(200),
  ENDPOINT VARCHAR(1000),
  HEALTHY INT,
  LATENCY_MS BIGINT,
  CHECKED_AT TIMESTAMP
);
CREATE INDEX IDX_SERVICE_METRICS_CHECKED_AT ON SERVICE_METRICS (CHECKED_AT);
